version: '3.2'
services:
  web:
    build:
      context: .
    image: redmine_plugin_dev
    container_name: redmine_plugin_dev
    command: >
      bash -c "bundle &&
           bundle exec rake db:migrate &&
           bundle exec rake redmine:plugins:migrate &&
           bundle exec rake generate_secret_token &&
           bundle exec rdebug-ide --debug --host 0.0.0.0 --port 1234  --dispatcher-port 26162 -- bin/rails s -p 3000 -b 0.0.0.0"
    environment:
      RAILS_ENV: development
    volumes:
      - ./:/app/redmine/plugins/redmine_work_report
      - ./data:/app/data
    ports:
      - "1234:1234"
      - "8083:3000"
      - "26162:26162"
